name: espic
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - scipy
  - matplotlib
  - pytest
  - furo
  - myst-parser
  - sphinx
  - sphinx-copybutton
  - sphinx-autodoc-typehints
